### ISSUE TITLE
Remove duplicate websocket connections

### ISSUE THREAD

**Issue by Mehavoid** [metarhia/metarhia.com#101]
![image](https://user-images.githubusercontent.com/63477090/104815865-6ae10500-5828-11eb-9e98-a30310c5d53b.png)
![image](https://user-images.githubusercontent.com/63477090/104797644-d26b6600-57d0-11eb-999c-d215ddb41213.png)
![image](https://user-images.githubusercontent.com/63477090/104797646-db5c3780-57d0-11eb-8ed8-f21e37fae983.png)

**Comment by tshemsedinov** [comment]
Fixed in metacom: https://github.com/metarhia/metacom/pull/284
