### ISSUE TITLE
Cert expired

### ISSUE THREAD

**Issue by OmgImAlexis** [metarhia/metarhia.com#119]
Might want to look into adding letsencrypt and enable auto-renewal.

<img width="499" alt="Screen Shot 2021-06-19 at 5 29 27 am" src="https://user-images.githubusercontent.com/6525926/122610776-5b0f6a80-d0bf-11eb-9a29-6f11c899e03a.png">

**Comment by tshemsedinov** [comment]
Thanks @OmgImAlexis, updated
