### ISSUE TITLE
Delete uploaded files after timeout

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metarhia.com#19]
- Delete will work hourly using Impress scheduler
- Default timeout will be 50 hours
- Maximum timeout will be 5 days
- File uploading api will support additional parameter to set timeout
- Web-based CLI need additional parameter but it may be added later with separate issue/commit after CLI refactoring because it is not flexible now

**Comment by DzyubSpirit** [comment]
@tshemsedinov, do you mean `application.tasks` and related folder by saying 'Impress scheduler'. It seems to not work now. Should an issue be opened in Impress accordingly?

**Comment by tshemsedinov** [comment]
Outdated
