### ISSUE TITLE
Connection recovery

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metarhia.com#29]
What about sessions and chat rooms on connection recovery?
@metarhia/server @metarhia/mobile @metarhia/jstp

**Comment by tshemsedinov** [comment]
We need at least following abilities:
- Display connection status in app, so we will not talk to nobody
- Reconnect to chat room

In future versions:
- Restore transfer of big files
- Rooms with history (so user can send there even if nobody other connected)
- Delivery status, to see message delivery status to other user

**Comment by nechaido** [comment]
> - Display connection status in app, so we will not talk to nobody

Currently the error will be send if there is no interlocutor.
There are events for users joining and leaving chats, but we will also add return value to `join` method, which will indicate whether the chat has someone in it already.

**Comment by tshemsedinov** [comment]
Outdated
