### ISSUE TITLE
User stays in chat for a long period after restoration of connection

### ISSUE THREAD

**Issue by GYFK** [metarhia/metarhia.com#39]
After the connection recovery (as issue in #29 ) the user is still considered present in a chatRoom, which makes him unable to immediately rejoin it. The user has to wait for some time in order to be removed and rejoin the chat.

**Comment by belochub** [comment]
I can use ping to verify if the users' connections in the room are still online when a new user tries to enter the room and remove unresponsive connections from the room to allow the new user to enter.
@tshemsedinov, @nechaido, what do you think about this solution?

**Comment by nechaido** [comment]
@belochub sounds ok.

**Comment by tshemsedinov** [comment]
Outdated
